FROM centos:latest
RUN yum install -y httpd \
zip \
unzip
ADD https://www.free-css.com/free-css-templates/page280/foodhut /var/www/html
WORKDIR /var/ww/html
RUN unzip photogenic.zip
RUN cp -rvf photogenic/* .
RUN rm -rf photogenic photogenic.zip
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
EXPOSE 80
